version: "3.9"
services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./serving/minio-data:/data

  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set local http://minio:9000 ${MINIO_ROOT_USER:-minioadmin} ${MINIO_ROOT_PASSWORD:-minioadmin} &&
      /usr/bin/mc mb -p local/${MINIO_BUCKET:-mlflow} || true &&
      tail -f /dev/null
      "

  mlflow:
    image: python:3.11-slim
    depends_on:
      - mc
    working_dir: /app
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER:-minioadmin}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "5000:5000"
    volumes:
      - ./serving/mlflow:/app
    command: >
      sh -c "pip install --no-cache-dir mlflow==2.14.1 boto3 &&
             mlflow server --backend-store-uri sqlite:///mlflow.db
                           --default-artifact-root s3://${MINIO_BUCKET:-mlflow}
                           --host 0.0.0.0 --port 5000"

  api:
    build: ./serving
    depends_on:
      - mlflow
    environment:
      - MODEL_PATH=/app/app/model.pkl
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    ports:
      - "8000:8000"
    volumes:
      - ./serving/app:/app/app
